Repository wantedPreOnboarding/19_02nd_slr_admin, pull requests merged in 2022-01, with the labels that each got.

#12 [영종] Add - 공통으로 사용될 테이블 설계 완료
  src/App.jsx
  src/App.module.css
  src/Components/BasicInfo/BasicInfo.js
  src/Components/BasicInfo/BasicInfo.module.css
  src/Components/Grid/Grid.jsx
  src/Components/Grid/Grid.module.css
  src/Components/Grid/constants.js
  src/Components/ProductOption/ProductOption.module.css
  src/Components/Table/Table.js
  src/Components/Table/Table.module.css
  src/Components/Table/TableHeader.js
  src/Components/Table/TableHeader.module.css
  src/Components/Table/TableRow.js
  src/Components/Table/TableRow.module.css
  src/Components/index.js
  src/styles/colors.css
  src/styles/index.module.css
  src/styles/theme.css
  src/utils/classNames.js
  src/utils/classNames.test.js
  src/utils/index.js
  src/utils/isCssUnit.js
  src/utils/isCssUnit.test.js
Labels: enhancement

#7 [송현] Add - Aside, ProductIntroImg, BuyerRecommendImg
  public/index.html
  src/App.jsx
  src/components/Aside/Aside.jsx
  src/components/Aside/Aside.module.css
  src/components/BuyerRecommendImg/BuyerRecommendImg.jsx
  src/components/BuyerRecommendImg/BuyerRecommendImg.module.css
  src/components/ProductIntroImg/ProductIntroImg.jsx
  src/components/ProductIntroImg/ProductIntroImg.module.css
  src/styles/index.module.css
Labels: style

#20 [영종] Add - 카테고리 체크박스 기능 구현, 폰트적용, Grid space 범위 조정, a11yHidden 추가
  public/index.html
  src/App.jsx
  src/App.module.css
  src/Components/BasicInfo/BasicInfo.js
  src/Components/BasicInfo/BasicInfo.module.css
  src/Components/CheckBox/CheckBox.js
  src/Components/Grid/Grid.jsx
  src/Components/Grid/Grid.module.scss
  src/Components/ProductOption/ProductOption.module.css
  src/styles/index.module.css
  src/utils/index.js
Labels: enhancement

#21 [송현] Modify - ProductIntro, BuyerRecommendImg
  src/App.jsx
  src/components/BuyerRecommendImg/BuyerRecommendImg.jsx
  src/components/BuyerRecommendImg/BuyerRecommendImg.module.css
  src/components/ProductIntroImg/ProductIntroImg.jsx
  src/components/ProductIntroImg/ProductIntroImg.module.css
Labels: style

#30 Modify - 토글버튼 공통 인풋 id사용문제 수정 및 Add- 마일리지,기타 컴포넌트 추가 및 스타일링
  src/App.jsx
  src/Components/MileageEtc/MileageEtc.jsx
  src/Components/MileageEtc/MileageEtc.module.css
  src/Components/ProductOption/ProductOption.jsx
  src/Components/ToggleBtn/ToggleBtn.jsx
  src/Components/index.js
Labels: bug, enhancement

#32 toggle 상태변경 기능 구현 & 마일리지 기타 컴포넌트 기능구현
  src/Components/MileageEtc/MileageEtc.jsx
  src/Components/MileageEtc/MileageEtc.module.css
  src/Components/ToggleBtn/ToggleBtn.jsx
Labels: enhancement

#34 [송현] Modify - 상품 정보 고시 추가
  src/App.jsx
  src/Components/MileageEtc/MileageEtc.module.css
  src/Components/ProductIntroNotice/ProductIntroNotice.jsx
  src/Components/ProductIntroNotice/ProductIntroNotice.module.css
  src/Components/Table/TableItem.jsx
  src/Components/Table/TableItem.module.scss
  src/Components/index.js
  src/components/BuyerRecommendImg/BuyerRecommendImg.jsx
  src/components/BuyerRecommendImg/BuyerRecommendImg.module.css
  src/components/ProductIntroImg/ProductIntroImg.jsx
  src/components/ProductIntroImg/ProductIntroImg.module.css
Labels: style

#38 Modify- 프로덕트옵션관련 컴포넌트 폴더구조 변경 및 마크업 변경 , Add-프로덕트 옵션 미리보기 추가, 프로덕트 옵션 삭제 생성 추가
  src/App.jsx
  src/Components/MileageEtc/MileageEtc.jsx
  src/Components/ProductOption/ProOptForm/ProOptForm.jsx
  src/Components/ProductOption/ProOptForm/ProOptForm.module.css
  src/Components/ProductOption/ProOptMain/ProOptMain.jsx
  src/Components/ProductOption/ProOptMain/ProOptMain.module.css
  src/Components/ProductOption/ProOptSet/ProOptSet.jsx
  src/Components/ProductOption/ProOptSet/ProOptSet.module.css
  src/Components/ProductOption/ProductOption.jsx
  src/Components/ProductOption/ProductOption.module.css
  src/Components/ProductOptionForm/ProductOptionForm.jsx
  src/Components/ProductOptionForm/ProductOptionForm.module.css
  src/Components/index.js
  src/styles/theme.css
Labels: enhancement

#40 [송현] Add - 상품 정보 고시 기능 구현
  src/Components/ProductIntroNotice/NoticeItem/NoticeItem.jsx
  src/Components/ProductIntroNotice/NoticeItem/NoticeItem.module.css
  src/Components/ProductIntroNotice/ProductIntroNotice.jsx
  src/Components/ProductIntroNotice/ProductIntroNotice.module.css
  src/Components/ToggleBtn/ToggleBtn.jsx
Labels: enhancement

#37 [다빈] Add - 날짜 선택 기능, 상품 노출 컴포넌트 기간 설정 기능, 상품 배송 설정 기능
  src/Components/ExposePeriod/ExposePeriod.jsx
  src/Components/ExposePeriod/ExposePeriod.module.css
  src/Components/ExposePeriod/ExposePeriodForm.jsx
  src/Components/FormDatePicker/FormDatePicker.jsx
  src/Components/FormDatePicker/FormDatePicker.module.css
  src/Components/ProductDelivery/ProductDelivery.jsx
  src/Components/ProductDelivery/ProductDelivery.module.scss
  src/Components/index.js
Labels: enhancement

#41 Modify 프로덕트 옵션, 토글 버튼 전체적인 코드정리
  src/App.jsx
  src/Components/MileageEtc/MileageEtc.jsx
  src/Components/ProductOption/ProOptForm/ProOptForm.jsx
  src/Components/ProductOption/ProOptForm/ProOptForm.module.css
  src/Components/ProductOption/ProOptMain/ProOptMain.jsx
  src/Components/ProductOption/ProOptSet/ProOptSet.jsx
  src/Components/ProductOption/ProOptSet/ProOptSet.module.css
  src/Components/ToggleBtn/ToggleBtn.jsx
Labels: style, enhancement, refactor

#42 [다빈] Modify - Input 폼에 require 추가, 날짜 입력 폼 크기 수정
  src/Components/ExposePeriod/ExposePeriod.jsx
  src/Components/ExposePeriod/ExposePeriod.module.scss
  src/Components/ExposePeriod/ExposePeriodForm.jsx
  src/Components/FormDatePicker/FormDatePicker.jsx
  src/Components/FormDatePicker/FormDatePicker.module.css
  src/Components/MileageEtc/MileageEtc.jsx
  src/Components/ProductDelivery/ProductDelivery.jsx
  src/Components/ProductDelivery/ProductDelivery.module.css
  src/Components/ProductDelivery/ProductDelivery.module.scss
  src/Components/ToggleBtn/ToggleBtn.jsx
Labels: enhancement

#50 Docs - 팀원 소개 순서 변경
  README.md
Labels: docs

#51 [송현] Fix - 이미지 추가 오류 해결
  README.md
  src/Components/BuyerRecommendImg/BuyerRecommendImg.jsx
  src/Components/ProductIntroImg/ProductIntroImg.jsx
  src/Components/ProductIntroNotice/NoticeItem/NoticeItem.jsx
  src/Components/ProductIntroNotice/NoticeItem/NoticeItem.module.css
  src/Components/ProductIntroNotice/ProductIntroNotice.jsx
  src/Components/ProductIntroNotice/ProductIntroNotice.module.css
Labels: bug
